[platformio]
src_dir = main

[env:atoms3-lite]
platform = espressif32
board = m5stack-atoms3
framework = espidf
monitor_speed = 115200
upload_speed = 1500000

; Flash settings for ATOMS3 Lite (8MB Flash)
board_build.flash_size = 8MB
board_build.partitions = partitions_8mb.csv

build_flags =
    -DCONFIG_HTTPD_WS_SUPPORT=1
    -DCONFIG_FREERTOS_HZ=1000
    -fexceptions

build_unflags =
    -fno-exceptions
