/*
 * This software is provided "as is" and any expressed or implied
 * warranties, including, but not limited to, the implied warranties of
 * merchantability and fitness for a particular purpose are disclaimed.
 * ROHM shall not be liable for any direct, indirect, consequential or 
 * incidental damages arising from using or modifying this software.
 * You (customer) can modify and use this software in whole or part on
 * your own responsibility, only for the purpose of developing the software
 * for use with microcontroller manufactured by ROHM.
 *
 * @file     C:/ML63Q25x7(Ver1.01)//ML63Q25x7.h
 * @brief    CMSIS HeaderFile
 * @version  1.01
 * @date     Mon Mar 24 11:30:38 2025
 * @note     Generated by SVDConv V3.3.44
 *           from File 'C:/ML63Q25x7(Ver1.01)/ML63Q25x7.svd',
 *           last modified on Mon Mar 24 11:30:11 2025
 */


/** @addtogroup ROHM Co.,Ltd.
  * @{
  */


/** @addtogroup ML63Q25x7
  * @{
  */


#ifndef ML63Q25X7_H
#define ML63Q25X7_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M0+ Specific Interrupt Numbers  ======================================= */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* =========================================  ML63Q25x7 Specific Interrupt Numbers  ========================================== */
  EXI_IRQn                  =   0,              /*!< 0  EXI                                                                    */
  TM0_IRQn                  =   1,              /*!< 1  TM0                                                                    */
  TM1_IRQn                  =   2,              /*!< 2  TM1                                                                    */
  FTM0_IRQn                 =   3,              /*!< 3  FTM0                                                                   */
  DMAC0_IRQn                =   4,              /*!< 4  DMAC0                                                                  */
  NTMS_IRQn                 =   5,              /*!< 5  NTMS                                                                   */
  SIOF1_IRQn                =   6,              /*!< 6  SIOF1                                                                  */
  MCU_IRQn                  =   7,              /*!< 7  MCU                                                                    */
  UAF1_IRQn                 =   8,              /*!< 8  UAF1                                                                   */
  TM2_IRQn                  =   9,              /*!< 9  TM2                                                                    */
  TM3_IRQn                  =  10,              /*!< 10 TM3                                                                    */
  FTM1_IRQn                 =  11,              /*!< 11 FTM1                                                                   */
  DMAC1_IRQn                =  12,              /*!< 12 DMAC1                                                                  */
  UAF3_IRQn                 =  13,              /*!< 13 UAF3                                                                   */
  SIOF0_IRQn                =  14,              /*!< 14 SIOF0                                                                  */
  I2CF0_IRQn                =  15,              /*!< 15 I2CF0                                                                  */
  UAF0_IRQn                 =  16,              /*!< 16 UAF0                                                                   */
  TM4_IRQn                  =  17,              /*!< 17 TM4                                                                    */
  TM5_IRQn                  =  18,              /*!< 18 TM5                                                                    */
  CMP_IRQn                  =  19,              /*!< 19 CMP                                                                    */
  CLK_IRQn                  =  20,              /*!< 20 CLK                                                                    */
  VLS_IRQn                  =  21,              /*!< 21 VLS                                                                    */
  SAD_IRQn                  =  22,              /*!< 22 SAD                                                                    */
  UAF2_IRQn                 =  23,              /*!< 23 UAF2                                                                   */
  AI_INT2_IRQn              =  24,              /*!< 24 AI_INT2                                                                */
  CAN0_INT0_IRQn            =  25,              /*!< 25 CAN0_INT0                                                              */
  CAN0_INT1_IRQn            =  26,              /*!< 26 CAN0_INT1                                                              */
  SAD1_IRQn                 =  27,              /*!< 27 SAD1                                                                   */
  RTC_IRQn                  =  28,              /*!< 28 RTC                                                                    */
  LTBC_IRQn                 =  29,              /*!< 29 LTBC                                                                   */
  TM1K_IRQn                 =  30,              /*!< 30 TM1K                                                                   */
  AI_INT_IRQn               =  31               /*!< 31 AI_INT                                                                 */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ==========================  Configuration of the ARM Cortex-M0+ Processor and Core Peripherals  =========================== */
#define __CM0PLUS_REV                 0x0001U   /*!< CM0PLUS Core Revision                                                     */
#define __NVIC_PRIO_BITS               2        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __VTOR_PRESENT                 0        /*!< Set to 1 if CPU supports Vector Table Offset Register                     */
#define __MPU_PRESENT                  0        /*!< MPU present                                                               */
#define __FPU_PRESENT                  0        /*!< FPU present                                                               */
#define __DSP_PRESENT                  0        /*!< DSP extension present                                                     */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm0plus.h"                       /*!< ARM Cortex-M0+ processor and core peripherals                             */
#include "system_ML63Q25x7.h"                   /*!< ML63Q25x7 System                                                          */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                         FLASHCNT                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief Flash controller (FLASHCNT)
  */

typedef struct {                                /*!< FLASHCNT Structure                                                        */
  __IOM uint32_t  FLASHA;                       /*!< Flash address register                                                    */
  __IOM uint32_t  FLASHD;                       /*!< Flash data register                                                       */
  __OM  uint32_t  FLASHCON;                     /*!< Flash control register                                                    */
  __OM  uint32_t  FLASHACP;                     /*!< Flash acceptor                                                            */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  FLASHSLF;                     /*!< Flash self register                                                       */
  __IM  uint32_t  FLASHSTA;                     /*!< Flash status register                                                     */
} FLASHCNT_Type;                                /*!< Size = 28 (0x1c)                                                          */



/* =========================================================================================================================== */
/* ================                                           RESET                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (RESET)
  */

typedef struct {                                /*!< RESET Structure                                                           */
  __IOM uint32_t  RSTAT;                        /*!< Reset status register                                                     */
  __IOM uint32_t  LOCKUPEN;                     /*!< LOCKUP reset setting register                                             */
  __OM  uint32_t  CPURST;                       /*!< CPU reset register                                                        */
  __IOM uint32_t  SRSCR;                        /*!< Software reset scratch register                                           */
  __IOM uint32_t  REMAPRSTEN;                   /*!< REMAP register reset enable register                                      */
} RESET_Type;                                   /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                          CLKCNT                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CLKCNT)
  */

typedef struct {                                /*!< CLKCNT Structure                                                          */
  __IOM uint32_t  FCON01;                       /*!< Frequency control register 01                                             */
  __IOM uint32_t  FCON23;                       /*!< Frequency control register 23                                             */
  __IM  uint32_t  FSTAT;                        /*!< Frequency status register                                                 */
  __IM  uint32_t  RESERVED[2];
  __IOM uint32_t  FCON67;                       /*!< Frequency control register 67                                             */
  __IOM uint32_t  FHWUPT;                       /*!< Clock startup control register                                            */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  FCON89;                       /*!< Frequency control register 89                                             */
  __IOM uint32_t  FSTAT2;                       /*!< Frequency status register 2                                               */
  __IM  uint32_t  RESERVED2[10];
  __IOM uint32_t  SYSCANMOD;                    /*!< CANCLK mode register                                                      */
  __IOM uint32_t  SYSNTMSMOD;                   /*!< NTMSCLK mode register                                                     */
} CLKCNT_Type;                                  /*!< Size = 88 (0x58)                                                          */



/* =========================================================================================================================== */
/* ================                                           NINT                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (NINT)
  */

typedef struct {                                /*!< NINT Structure                                                            */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  EXIST;                        /*!< External Interrupt status register                                        */
  __IOM uint32_t  EXICON;                       /*!< External interrupt control register                                       */
  __IOM uint32_t  EXI03SEL;                     /*!< External interrupt 03 selection register                                  */
  __IOM uint32_t  EXI47SEL;                     /*!< External interrupt 47 selection register                                  */
  __IM  uint32_t  RESERVED1[3];
  __IOM uint32_t  TCKI03SEL;                    /*!< Timer clock input 03 selection register                                   */
  __IOM uint32_t  TCKI47SEL;                    /*!< Timer clock input 47 selection register                                   */
} NINT_Type;                                    /*!< Size = 40 (0x28)                                                          */



/* =========================================================================================================================== */
/* ================                                           DMAC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC)
  */

typedef struct {                                /*!< DMAC Structure                                                            */
  __IOM uint32_t  DMAMOD;                       /*!< DMA mode register                                                         */
  __IM  uint32_t  DMASTA;                       /*!< DMA status register                                                       */
  __IM  uint32_t  DMAINT;                       /*!< DMA end status register                                                   */
} DMAC_Type;                                    /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                           DMAC0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC0)
  */

typedef struct {                                /*!< DMAC0 Structure                                                           */
  __IOM uint32_t  DMACMSK0;                     /*!< DMA channel mask register                                                 */
  __IOM uint32_t  DMACTMOD0;                    /*!< DMA transfer mode register                                                */
  __IOM uint32_t  DMACSAD0;                     /*!< DMA transfer source address register                                      */
  __IOM uint32_t  DMACDAD0;                     /*!< DMA transfer destination address register                                 */
  __IOM uint32_t  DMACSIZ0;                     /*!< DMA transfer count register                                               */
  __OM  uint32_t  DMACCINT0;                    /*!< DMA end status clear register                                             */
} DMACn_Type;                                   /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           DMAC1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC1)
  */

typedef struct {                                /*!< DMAC1 Structure                                                           */
  __IOM uint32_t  DMACMSK1;                     /*!< DMA channel mask register                                                 */
  __IOM uint32_t  DMACTMOD1;                    /*!< DMA transfer mode register                                                */
  __IOM uint32_t  DMACSAD1;                     /*!< DMA transfer source address register                                      */
  __IOM uint32_t  DMACDAD1;                     /*!< DMA transfer destination address register                                 */
  __IOM uint32_t  DMACSIZ1;                     /*!< DMA transfer count register                                               */
  __OM  uint32_t  DMACCINT1;                    /*!< DMA end status clear register                                             */
} DMACn1_Type;                                  /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           LTBC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (LTBC)
  */

typedef struct {                                /*!< LTBC Structure                                                            */
  __IOM uint32_t  LTBR;                         /*!< Low-speed time base counter register                                      */
  __IOM uint32_t  LTBADJ;                       /*!< Low-speed time base counter frequency adjustment register                 */
  __IOM uint32_t  LTBINT;                       /*!< Low-speed time base counter interrupt select resister                     */
  __IOM uint32_t  LTBCINTST;                    /*!< Low-speed time base counter interrupt status register                     */
  __IM  uint32_t  LTBRR;                        /*!< Low-speed time base counter for RTC register                              */
} LTBC_Type;                                    /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                           TIMER                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TIMER)
  */

typedef struct {                                /*!< TIMER Structure                                                           */
  __IOM uint32_t  TM0D;                         /*!< Timer 0 data register                                                     */
  __IOM uint32_t  TM0C;                         /*!< Timer 0 counter register                                                  */
  __IOM uint32_t  TM0CON;                       /*!< Timer 0 control register                                                  */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  TM1D;                         /*!< Timer 1 data register                                                     */
  __IOM uint32_t  TM1C;                         /*!< Timer 1 counter register                                                  */
  __IOM uint32_t  TM1CON;                       /*!< Timer 1 control register                                                  */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  TM2D;                         /*!< Timer 2 data register                                                     */
  __IOM uint32_t  TM2C;                         /*!< Timer 2 counter register                                                  */
  __IOM uint32_t  TM2CON;                       /*!< Timer 2 control register                                                  */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  TM3D;                         /*!< Timer 3 data register                                                     */
  __IOM uint32_t  TM3C;                         /*!< Timer 3 counter register                                                  */
  __IOM uint32_t  TM3CON;                       /*!< Timer 3 control register                                                  */
  __IM  uint32_t  RESERVED3;
  __IOM uint32_t  TM4D;                         /*!< Timer 4 data register                                                     */
  __IOM uint32_t  TM4C;                         /*!< Timer 4 counter register                                                  */
  __IOM uint32_t  TM4CON;                       /*!< Timer 4 control register                                                  */
  __IM  uint32_t  RESERVED4;
  __IOM uint32_t  TM5D;                         /*!< Timer 5 data register                                                     */
  __IOM uint32_t  TM5C;                         /*!< Timer 5 counter register                                                  */
  __IOM uint32_t  TM5CON;                       /*!< Timer 5 control register                                                  */
  __IM  uint32_t  RESERVED5[37];
  __OM  uint32_t  TMSTR;                        /*!< Timer start register                                                      */
  __OM  uint32_t  TMSTP;                        /*!< Timer stop register                                                       */
  __IM  uint32_t  TMSTAT;                       /*!< Timer status register                                                     */
} TIMER_Type;                                   /*!< Size = 252 (0xfc)                                                         */



/* =========================================================================================================================== */
/* ================                                          FTIMER                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (FTIMER)
  */

typedef struct {                                /*!< FTIMER Structure                                                          */
  __IOM uint32_t  FT0P;                         /*!< FTM0 period register                                                      */
  __IOM uint32_t  FT0EA;                        /*!< FTM0 event register A                                                     */
  __IOM uint32_t  FT0EB;                        /*!< FTM0 event register B                                                     */
  __IOM uint32_t  FT0DT;                        /*!< FTM0 dead time register                                                   */
  __IOM uint32_t  FT0C;                         /*!< FTM0 counter register                                                     */
  __IOM uint32_t  FT0CON0;                      /*!< FTM0 control register 0                                                   */
  __IOM uint32_t  FT0CON1;                      /*!< FTM0 control register 1                                                   */
  __IOM uint32_t  FT0MOD;                       /*!< FTM0 mode register                                                        */
  __IOM uint32_t  FT0CLK;                       /*!< FTM0 clock register                                                       */
  __IOM uint32_t  FT0TRG;                       /*!< FTM0 trigger register                                                     */
  __IM  uint32_t  RESERVED[2];
  __IOM uint32_t  FT0INTE;                      /*!< FTM0 interrupt enable register                                            */
  __IM  uint32_t  FT0INTS;                      /*!< FTM0 interrupt status register                                            */
  __OM  uint32_t  FT0INTC;                      /*!< FTM0 interrupt clear register                                             */
  __IM  uint32_t  RESERVED1[49];
  __IOM uint32_t  FT1P;                         /*!< FTM1 period register                                                      */
  __IOM uint32_t  FT1EA;                        /*!< FTM1 event register A                                                     */
  __IOM uint32_t  FT1EB;                        /*!< FTM1 event register B                                                     */
  __IOM uint32_t  FT1DT;                        /*!< FTM1 dead time register                                                   */
  __IOM uint32_t  FT1C;                         /*!< FTM1 counter register                                                     */
  __IOM uint32_t  FT1CON0;                      /*!< FTM1 control register 0                                                   */
  __IOM uint32_t  FT1CON1;                      /*!< FTM1 control register 1                                                   */
  __IOM uint32_t  FT1MOD;                       /*!< FTM1 mode register                                                        */
  __IOM uint32_t  FT1CLK;                       /*!< FTM1 clock register                                                       */
  __IOM uint32_t  FT1TRG;                       /*!< FTM1 trigger register                                                     */
  __IM  uint32_t  RESERVED2[2];
  __IOM uint32_t  FT1INTE;                      /*!< FTM1 interrupt enable register                                            */
  __IM  uint32_t  FT1INTS;                      /*!< FTM1 interrupt status register                                            */
  __OM  uint32_t  FT1INTC;                      /*!< FTM1 interrupt clear register                                             */
  __IM  uint32_t  RESERVED3[881];
  __IOM uint32_t  FTOSL0;                       /*!< FTM output select register 0                                              */
  __IOM uint32_t  FTOSL4;                       /*!< FTM output select register 4                                              */
} FTIMER_Type;                                  /*!< Size = 3848 (0xf08)                                                       */



/* =========================================================================================================================== */
/* ================                                            RTC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (RTC)
  */

typedef struct {                                /*!< RTC Structure                                                             */
  __IOM uint32_t  RTCSEC;                       /*!< Real time clock second register                                           */
  __IOM uint32_t  RTCMIN;                       /*!< Real time clock minute register                                           */
  __IOM uint32_t  RTCHOUR;                      /*!< Real time clock hour register                                             */
  __IOM uint32_t  RTCWEEK;                      /*!< Real time clock week register                                             */
  __IOM uint32_t  RTCDAY;                       /*!< Real time clock day register                                              */
  __IOM uint32_t  RTCMON;                       /*!< Real time clock month register                                            */
  __IOM uint32_t  RTCYEAR;                      /*!< Real time clock year register                                             */
  __IOM uint32_t  RTCCON;                       /*!< Real time clock control register                                          */
  __IOM uint32_t  AL0MIN;                       /*!< Real time clock alarm 0 minute register                                   */
  __IOM uint32_t  AL0HOUR;                      /*!< Real time clock alarm 0 hour register                                     */
  __IOM uint32_t  AL0WEEK;                      /*!< Real time clock alarm 0 week register                                     */
  __IOM uint32_t  AL1MIN;                       /*!< Real time clock alarm 1 minute register                                   */
  __IOM uint32_t  AL1HOUR;                      /*!< Real time clock alarm 1 hour register                                     */
  __IOM uint32_t  AL1DAY;                       /*!< Real time clock alarm 1 day register                                      */
  __IOM uint32_t  AL1MON;                       /*!< Real time clock alarm 1 month register                                    */
  __IM  uint32_t  RESERVED[5];
  __IM  uint32_t  RTCHMS;                       /*!< Real time clock hour/minute/second register                               */
  __IM  uint32_t  RTCYMDW;                      /*!< Real time clock year/month/day/week register                              */
  __IM  uint32_t  RESERVED1[2];
  __IOM uint32_t  RTCINTST;                     /*!< Real time clock interrupt statusregister                                  */
} RTC_Type;                                     /*!< Size = 100 (0x64)                                                         */



/* =========================================================================================================================== */
/* ================                                          TIMER1K                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TIMER1K)
  */

typedef struct {                                /*!< TIMER1K Structure                                                         */
  __IOM uint32_t  T1KCR;                        /*!< 1 kHz timer count register                                                */
  __IOM uint32_t  T1KCON;                       /*!< 1 kHz timer control register                                              */
} TIMER1K_Type;                                 /*!< Size = 8 (0x8)                                                            */



/* =========================================================================================================================== */
/* ================                                            WDT                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (WDT)
  */

typedef struct {                                /*!< WDT Structure                                                             */
  __IOM uint32_t  WDTCON;                       /*!< Watchdog timer control register                                           */
  __IOM uint32_t  WDTMOD;                       /*!< Watchdog timer mode register                                              */
} WDT_Type;                                     /*!< Size = 8 (0x8)                                                            */



/* =========================================================================================================================== */
/* ================                                          SSIOF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SSIOF0)
  */

typedef struct {                                /*!< SSIOF0 Structure                                                          */
  __IOM uint32_t  SF0CTRL;                      /*!< SIOF0 control register                                                    */
  __IOM uint32_t  SF0INTC;                      /*!< SIOF0 interrupt control register                                          */
  __IOM uint32_t  SF0TRAC;                      /*!< SIOF0 transfer interval control register                                  */
  __IOM uint32_t  SF0BRR;                       /*!< SIOF0 baud rate register                                                  */
  __IM  uint32_t  SF0SRR;                       /*!< SIOF0 status register                                                     */
  __OM  uint32_t  SF0SRC;                       /*!< SIOF0 status clear register                                               */
  __IM  uint32_t  SF0FSR;                       /*!< SIOF0 FIFO status register                                                */
  __IOM uint32_t  SF0DWR;                       /*!< SIOF0 write data register                                                 */
  __IM  uint32_t  SF0DRR;                       /*!< SIOF0 read data register                                                  */
} SSIOFn_Type;                                  /*!< Size = 36 (0x24)                                                          */



/* =========================================================================================================================== */
/* ================                                          SSIOF1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SSIOF1)
  */

typedef struct {                                /*!< SSIOF1 Structure                                                          */
  __IOM uint32_t  SF1CTRL;                      /*!< SIOF1 control register                                                    */
  __IOM uint32_t  SF1INTC;                      /*!< SIOF1 interrupt control register                                          */
  __IOM uint32_t  SF1TRAC;                      /*!< SIOF1 transfer interval control register                                  */
  __IOM uint32_t  SF1BRR;                       /*!< SIOF1 baud rate register                                                  */
  __IM  uint32_t  SF1SRR;                       /*!< SIOF1 status register                                                     */
  __OM  uint32_t  SF1SRC;                       /*!< SIOF1 status clear register                                               */
  __IM  uint32_t  SF1FSR;                       /*!< SIOF1 FIFO status register                                                */
  __IOM uint32_t  SF1DWR;                       /*!< SIOF1 write data register                                                 */
  __IM  uint32_t  SF1DRR;                       /*!< SIOF1 read data register                                                  */
} SSIOFn1_Type;                                 /*!< Size = 36 (0x24)                                                          */



/* =========================================================================================================================== */
/* ================                                          UARTF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (UARTF0)
  */

typedef struct {                                /*!< UARTF0 Structure                                                          */
  __IOM uint32_t  UAF0BUF;                      /*!< UARTF0 transmit/receive buffer                                            */
  __IOM uint32_t  UAF0IER;                      /*!< UARTF0 interrupt enable register                                          */
  __IM  uint32_t  UAF0IIR;                      /*!< UARTF0 interrupt status register                                          */
  __IOM uint32_t  UAF0MOD;                      /*!< UARTF0 mode register                                                      */
  __IM  uint32_t  UAF0LSR;                      /*!< UARTF0 line status register                                               */
  __IOM uint32_t  UAF0CAJ;                      /*!< UARTF0 clock adjustment register                                          */
} UARTFn_Type;                                  /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           I2CF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (I2CF0)
  */

typedef struct {                                /*!< I2CF0 Structure                                                           */
  __IOM uint32_t  I2F0SAD;                      /*!< I2CF0 slave address register                                              */
  __IOM uint32_t  I2F0CTL;                      /*!< I2CF0 control register                                                    */
  __IOM uint32_t  I2F0SR;                       /*!< I2CF0 status register                                                     */
  __IOM uint32_t  I2F0DR;                       /*!< I2CF0 data register                                                       */
  __IM  uint32_t  I2F0MON;                      /*!< I2CF0 bus monitor register                                                */
  __IOM uint32_t  I2F0BC;                       /*!< I2CF0 bus transfer rate setup counter                                     */
  __IOM uint32_t  I2F0MOD;                      /*!< I2CF0 mode register                                                       */
  __IOM uint32_t  I2F0BSV;                      /*!< I2CF0 buffer mode slave address register                                  */
  __IOM uint32_t  I2F0BSB;                      /*!< I2CF0 buffer mode sub address register                                    */
  __IOM uint32_t  I2F0BFR;                      /*!< I2CF0 buffer mode format register                                         */
  __IOM uint32_t  I2F0BCT;                      /*!< I2CF0 buffer mode control register                                        */
  __IOM uint32_t  I2F0BMK;                      /*!< I2CF0 buffer mode interrupt mask register                                 */
  __IOM uint32_t  I2F0BSR;                      /*!< I2CF0 buffer mode status register                                         */
  __IOM uint32_t  I2F0BLV;                      /*!< I2CF0 buffer mode level register                                          */
  __IM  uint32_t  RESERVED[4];
  __IOM uint32_t  I2F0TMR;                      /*!< I2CF0 timer register                                                      */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  I2F0NF;                       /*!< I2CF0 input noise filter setting register                                 */
} I2CFn_Type;                                   /*!< Size = 84 (0x54)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT2                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT2)
  */

typedef struct {                                /*!< PORT2 Structure                                                           */
  __IOM uint32_t  P2DI;                         /*!< -                                                                         */
  __IOM uint32_t  P2DO;                         /*!< -                                                                         */
  __IOM uint32_t  P2MOD0;                       /*!< -                                                                         */
} PORTn_Type;                                   /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                           PORT3                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT3)
  */

typedef struct {                                /*!< PORT3 Structure                                                           */
  __IOM uint32_t  P3DI;                         /*!< Port3 data input register                                                 */
  __IOM uint32_t  P3DO;                         /*!< Port3 data output register                                                */
  __IOM uint32_t  P3MOD0;                       /*!< Port3 mode register 0                                                     */
  __IOM uint32_t  P3MOD1;                       /*!< Port3 mode register 1                                                     */
} PORTn1_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT4                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT4)
  */

typedef struct {                                /*!< PORT4 Structure                                                           */
  __IOM uint32_t  P4DI;                         /*!< Port4 data input register                                                 */
  __IOM uint32_t  P4DO;                         /*!< Port4 data output register                                                */
  __IOM uint32_t  P4MOD0;                       /*!< Port4 mode register 0                                                     */
  __IOM uint32_t  P4MOD1;                       /*!< Port4 mode register 1                                                     */
} PORTn2_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT5                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT5)
  */

typedef struct {                                /*!< PORT5 Structure                                                           */
  __IOM uint32_t  P5DI;                         /*!< Port5 data input register                                                 */
  __IOM uint32_t  P5DO;                         /*!< Port5 data output register                                                */
  __IOM uint32_t  P5MOD0;                       /*!< Port5 mode register 0                                                     */
  __IOM uint32_t  P5MOD1;                       /*!< Port5 mode register 1                                                     */
} PORTn3_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT6                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT6)
  */

typedef struct {                                /*!< PORT6 Structure                                                           */
  __IOM uint32_t  P6DI;                         /*!< Port6 data input register                                                 */
  __IOM uint32_t  P6DO;                         /*!< Port6 data output register                                                */
  __IOM uint32_t  P6MOD0;                       /*!< Port6 mode register 0                                                     */
  __IOM uint32_t  P6MOD1;                       /*!< Port6 mode register 1                                                     */
} PORTn4_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT7                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT7)
  */

typedef struct {                                /*!< PORT7 Structure                                                           */
  __IOM uint32_t  P7DI;                         /*!< Port7 data input register                                                 */
  __IOM uint32_t  P7DO;                         /*!< Port7 data output register                                                */
  __IOM uint32_t  P7MOD0;                       /*!< Port7 mode register 0                                                     */
  __IOM uint32_t  P7MOD1;                       /*!< Port7 mode register 1                                                     */
} PORTn5_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT8                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT8)
  */

typedef struct {                                /*!< PORT8 Structure                                                           */
  __IOM uint32_t  P8DI;                         /*!< Port8 data input register                                                 */
  __IOM uint32_t  P8DO;                         /*!< Port8 data output register                                                */
  __IOM uint32_t  P8MOD0;                       /*!< Port8 mode register 0                                                     */
  __IOM uint32_t  P8MOD1;                       /*!< Port8 mode register 1                                                     */
} PORTn6_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           SADC0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SADC0)
  */

typedef struct {                                /*!< SADC0 Structure                                                           */
  __IOM uint32_t  SADMOD;                       /*!< SA-ADC Mode Register                                                      */
  __IOM uint32_t  SADCON;                       /*!< SA-ADC Control Register                                                   */
  __IOM uint32_t  SADSTM;                       /*!< SA-ADC Conversion Interval Register                                       */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  SADIMOD;                      /*!< SA-ADC Interrupt Mode Register                                            */
  __IOM uint32_t  SADTRG;                       /*!< SA-ADC Trigger Register                                                   */
  __IOM uint32_t  SADEN;                        /*!< SA-ADC Enable Register                                                    */
  __IOM uint32_t  SADLMOD;                      /*!< SA-ADC Upper/Lower Limit Mode Register                                    */
  __IOM uint32_t  SADUPL;                       /*!< SA-ADC Upper Limit Setting Register                                       */
  __IOM uint32_t  SADLOL;                       /*!< SA-ADC Lower Limit Setting Register                                       */
  __IM  uint32_t  SADULS;                       /*!< SA-ADC Upper/Lower Limit Status Register                                  */
  __OM  uint32_t  SADULC;                       /*!< SA-ADC Upper/Lower Limit Status Clear Register                            */
  __IOM uint32_t  SADTMOD;                      /*!< SA-ADC Test Mode Register                                                 */
  __IM  uint32_t  SADR;                         /*!< SA-ADC Result Register                                                    */
  __IM  uint32_t  SADR0;                        /*!< SA-ADC Result Register0                                                   */
  __IM  uint32_t  SADR1;                        /*!< SA-ADC Result Register1                                                   */
  __IM  uint32_t  SADR2;                        /*!< SA-ADC Result Register2                                                   */
  __IM  uint32_t  SADR3;                        /*!< SA-ADC Result Register3                                                   */
  __IM  uint32_t  SADR4;                        /*!< SA-ADC Result Register4                                                   */
  __IM  uint32_t  SADR5;                        /*!< SA-ADC Result Register5                                                   */
  __IM  uint32_t  SADR6;                        /*!< SA-ADC Result Register6                                                   */
  __IM  uint32_t  SADR7;                        /*!< SA-ADC Result Register7                                                   */
  __IM  uint32_t  SADR8;                        /*!< SA-ADC Result Register8                                                   */
  __IM  uint32_t  SADR9;                        /*!< SA-ADC Result Register9                                                   */
  __IM  uint32_t  SADR10;                       /*!< SA-ADC Result Register10                                                  */
  __IM  uint32_t  SADR11;                       /*!< SA-ADC Result Register11                                                  */
} SADCn_Type;                                   /*!< Size = 104 (0x68)                                                         */



/* =========================================================================================================================== */
/* ================                                            CMP                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CMP)
  */

typedef struct {                                /*!< CMP Structure                                                             */
  __IOM uint32_t  CMPCON;                       /*!< Analog-compalator control                                                 */
  __IOM uint32_t  CMP0MOD;                      /*!< Analog-compalator 0 mode                                                  */
  __IOM uint32_t  CMP1MOD;                      /*!< Analog-compalator 1 mode                                                  */
  __IOM uint32_t  CMP2MOD;                      /*!< Analog-compalator 2 mode                                                  */
  __IM  uint32_t  RESERVED[5];
  __IOM uint32_t  CMPINTS;                      /*!< Analog-compalator interrupt staus                                         */
} CMP_Type;                                     /*!< Size = 40 (0x28)                                                          */



/* =========================================================================================================================== */
/* ================                                            VLS                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (VLS)
  */

typedef struct {                                /*!< VLS Structure                                                             */
  __IOM uint32_t  VLS0CON;                      /*!< Voltage level supervisor control register                                 */
  __IOM uint32_t  VLS0MOD;                      /*!< Voltage level supervisor mode register                                    */
  __IOM uint32_t  VLS0LV;                       /*!< Voltage level supervisor level register                                   */
  __IOM uint32_t  VLS0SMP;                      /*!< Voltage level supervisor sampling register                                */
  __IM  uint32_t  VLS0STS;                      /*!< Voltage level supervisor status register                                  */
  __OM  uint32_t  VLS0STC;                      /*!< Voltage level supervisor status clear register                            */
} VLS_Type;                                     /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                          LSICNT                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (LSICNT)
  */

typedef struct {                                /*!< LSICNT Structure                                                          */
  __IM  uint32_t  IDR;                          /*!< Revision Register                                                         */
  __IOM uint32_t  DREQSEL;                      /*!< DMA Request Select register                                               */
  __IOM uint32_t  BRMPNCON;                     /*!< BRMPN Control Register                                                    */
  __IM  uint32_t  UIDR;                         /*!< Unique ID Register                                                        */
  __IOM uint32_t  REMAPCON;                     /*!< Remapping Control Register                                                */
  __IOM uint32_t  REMAPBASE;                    /*!< Remapping Control Register                                                */
  __IM  uint32_t  RESERVED[10];
  __IOM uint32_t  FLAWAIT;                      /*!< Flash wait setting Register                                               */
  __IOM uint32_t  SBYCON;                       /*!< Standby Control Register                                                  */
  __IOM uint32_t  PMCON;                        /*!< Power Management Control Register                                         */
  __IOM uint32_t  CLKCON;                       /*!< Clock Control Register                                                    */
  __IOM uint32_t  RSTCON;                       /*!< Reset Control Register                                                    */
  __IOM uint32_t  AI_MEMSEL;                    /*!< AI ram select register                                                    */
  __IOM uint32_t  AI_INTSEL;                    /*!< AI interrupt select register                                              */
  __IOM uint32_t  MCUINTEN;                     /*!< MCU interrupt enable register                                             */
  __IOM uint32_t  MCUISTAT;                     /*!< MCU interrupt status                                                      */
} LSICNT_Type;                                  /*!< Size = 100 (0x64)                                                         */



/* =========================================================================================================================== */
/* ================                                            CRC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CRC)
  */

typedef struct {                                /*!< CRC Structure                                                             */
  __IOM uint32_t  CRCDATA;                      /*!< CRC calculation data register                                             */
  __IOM uint32_t  CRCRES;                       /*!< CRC calculation result register                                           */
  __IOM uint32_t  CRCMOD;                       /*!< CRC calculation mode register                                             */
} CRC_Type;                                     /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                            AI                                             ================ */
/* =========================================================================================================================== */


/**
  * @brief - (AI)
  */

typedef struct {                                /*!< AI Structure                                                              */
  __IOM uint32_t  ML_ACC_CTRL0;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL1;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL2;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL3;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL4;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL5;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL6;                 /*!< -                                                                         */
  __IOM uint32_t  ML_ACC_CTRL7;                 /*!< -                                                                         */
} AI_Type;                                      /*!< Size = 32 (0x20)                                                          */



/* =========================================================================================================================== */
/* ================                                           CAN0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief CAN Controler (CAN0)
  */

typedef struct {                                /*!< CAN0 Structure                                                            */
  __IM  uint32_t  CANCREL;                      /*!< Version number register                                                   */
  __IM  uint32_t  CANENDN;                      /*!< Endian test register                                                      */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  CANDBTP;                      /*!< FD bit timing register                                                    */
  __IOM uint32_t  CANTEST;                      /*!< Test register                                                             */
  __IOM uint32_t  CANRWD;                       /*!< RAM Watchdog register                                                     */
  __IOM uint32_t  CANCCCR;                      /*!< CAN FD controller control register                                        */
  __IOM uint32_t  CANNBTP;                      /*!< Bit timing register                                                       */
  __IOM uint32_t  CANTSCC;                      /*!< Time stamp counter setting register                                       */
  __IOM uint32_t  CANTSCV;                      /*!< Time stamp counter value register                                         */
  __IOM uint32_t  CANTOCC;                      /*!< Timeout counter setting register                                          */
  __IOM uint32_t  CANTOCV;                      /*!< Timeout counter value register                                            */
  __IM  uint32_t  RESERVED1[4];
  __IM  uint32_t  CANECR;                       /*!< Error counter register                                                    */
  __IOM uint32_t  CANPSR;                       /*!< Protocol status register                                                  */
  __IOM uint32_t  CANTDCR;                      /*!< Transmitter delay correction register                                     */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  CANIR;                        /*!< Interrupt register                                                        */
  __IOM uint32_t  CANIE;                        /*!< Interrupt enable register                                                 */
  __IOM uint32_t  CANILS;                       /*!< Interrupt signal selection register                                       */
  __IOM uint32_t  CANILE;                       /*!< Interrupt signal enable register                                          */
  __IM  uint32_t  RESERVED3[8];
  __IOM uint32_t  CANGFC;                       /*!< Global filter configuration register                                      */
  __IOM uint32_t  CANSIDFC;                     /*!< Standard ID filter configuration register                                 */
  __IOM uint32_t  CANXIDFC;                     /*!< Extended ID filter configuration register                                 */
  __IM  uint32_t  RESERVED4;
  __IOM uint32_t  CANXIDAM;                     /*!< Extended ID mask register                                                 */
  __IM  uint32_t  CANHPMS;                      /*!< High priority message status register                                     */
  __IOM uint32_t  CANNDAT1;                     /*!< Specific ID receive message 1 register                                    */
  __IOM uint32_t  CANNDAT2;                     /*!< Specific ID receive message 2 register                                    */
  __IOM uint32_t  CANRXF0C;                     /*!< Rx FIFO 0 configuration register                                          */
  __IM  uint32_t  CANRXF0S;                     /*!< Rx FIFO 0 status register                                                 */
  __IOM uint32_t  CANRXF0A;                     /*!< Rx FIFO 0 acknowledge register                                            */
  __IOM uint32_t  CANRXBC;                      /*!< Rx buffer configuration register                                          */
  __IOM uint32_t  CANRXF1C;                     /*!< Rx FIFO 1 configuration register                                          */
  __IM  uint32_t  CANRXF1S;                     /*!< Rx FIFO 1 status register                                                 */
  __IOM uint32_t  CANRXF1A;                     /*!< Rx FIFO 1 acknowledge register                                            */
  __IOM uint32_t  CANRXESC;                     /*!< Rx buffer/FIFO element size configuration register                        */
  __IOM uint32_t  CANTXBC;                      /*!< Tx buffer configuration register                                          */
  __IM  uint32_t  CANTXFQS;                     /*!< Tx FIFO/queue status register                                             */
  __IOM uint32_t  CANTXESC;                     /*!< Tx buffer element size Configuration register                             */
  __IM  uint32_t  CANTXBRP;                     /*!< Tx buffer request pending register                                        */
  __IOM uint32_t  CANTXBAR;                     /*!< Tx buffer additional request register                                     */
  __IOM uint32_t  CANTXBCR;                     /*!< Tx buffer cancellation request register                                   */
  __IM  uint32_t  CANTXBTO;                     /*!< Tx buffer transmit occurrence register                                    */
  __IM  uint32_t  CANTXBCF;                     /*!< Tx buffer cancellation finish register                                    */
  __IOM uint32_t  CANTXBTIE;                    /*!< Tx buffer transmit interrupt enable register                              */
  __IOM uint32_t  CANTXBCIE;                    /*!< Tx buffer cancellation complete interrupt enable register                 */
  __IM  uint32_t  RESERVED5[2];
  __IOM uint32_t  CANTXEFC;                     /*!< Tx event FIFO configuration register                                      */
  __IM  uint32_t  CANTXEFS;                     /*!< Tx event FIFO status register                                             */
  __IOM uint32_t  CANTXEFA;                     /*!< Tx event FIFO acknowledge register                                        */
} CANn_Type;                                    /*!< Size = 252 (0xfc)                                                         */



/* =========================================================================================================================== */
/* ================                                        TMR0_COMMON                                        ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TMR0_COMMON)
  */

typedef struct {                                /*!< TMR0_COMMON Structure                                                     */
  __IOM uint32_t  TMON;                         /*!< Timer start register                                                      */
  __OM  uint32_t  TMOFF;                        /*!< Timer stop register                                                       */
  __IM  uint32_t  RESERVED[15];
  __IOM uint32_t  TMBRK;                        /*!< Timer Break setting register                                              */
  __IOM uint32_t  TMBE;                         /*!< Timer buffer control register                                             */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  TMES;                         /*!< Timer emergency processing start register                                 */
  __IOM uint32_t  TMEE;                         /*!< Timer emergency processing stop register                                  */
  __IM  uint32_t  RESERVED2[26];
  __IOM uint32_t  TMGMSEL;                      /*!< Timer emergency stop trigger select register                              */
  __IOM uint32_t  TMGMC;                        /*!< Timer emergency stop trigger processing register                          */
  __IOM uint32_t  TMOPT;                        /*!< Timer option register                                                     */
} TMR0_COMMON_Type;                             /*!< Size = 204 (0xcc)                                                         */



/* =========================================================================================================================== */
/* ================                                        TMR0_NTMS00                                        ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TMR0_NTMS00)
  */

typedef struct {                                /*!< TMR0_NTMS00 Structure                                                     */
  __IOM uint32_t  TMD;                          /*!< NTMS timer mode select register                                           */
  __IOM uint32_t  TMCTL;                        /*!< NTMS timer mode control register                                          */
  __IOM uint32_t  TMLEN;                        /*!< NTMS timer period setting register                                        */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  TMTG;                         /*!< NTMS timer input trigger setting register                                 */
  __IOM uint32_t  TMLENB;                       /*!< NTMS timer period setting buffer register                                 */
  __IM  uint32_t  RESERVED1[2];
  __IOM uint32_t  TMTHA0;                       /*!< NTMS timer waveform threshold setting register A0                         */
  __IOM uint32_t  TMTHA1;                       /*!< NTMS timer waveform threshold setting register A1                         */
  __IOM uint32_t  TMTHB0;                       /*!< NTMS timer waveform threshold setting register B0                         */
  __IOM uint32_t  TMTHB1;                       /*!< NTMS timer waveform threshold setting register B1                         */
  __IOM uint32_t  TMTHA0B;                      /*!< NTMS timer waveform threshold setting register A0B                        */
  __IOM uint32_t  TMTHA1B;                      /*!< NTMS timer waveform threshold setting register A1B                        */
  __IOM uint32_t  TMGM;                         /*!< NTMS timer emergency stop setting register                                */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  TMIMSK;                       /*!< NTMS timer interrupt mask register                                        */
  __IOM uint32_t  TMISTS;                       /*!< NTMS timer interrupt status register                                      */
  __IOM uint32_t  TMISTR;                       /*!< NTMS timer RAW interrupt status register                                  */
  __IM  uint32_t  RESERVED3;
  __IOM uint32_t  TMMON;                        /*!< NTMS timer count monitor register                                         */
  __IM  uint32_t  RESERVED4[2];
  __IM  uint32_t  TMEST;                        /*!< NTMS timer status register                                                */
  __IOM uint32_t  TMTHB0B;                      /*!< NTMS timer waveform threshold setting buffer register B0B                 */
  __IOM uint32_t  TMTHB1B;                      /*!< NTMS timer waveform threshold setting buffer register B1B                 */
  __IOM uint32_t  TMDBU;                        /*!< NTMS timer waveform dead time setting register                            */
  __IOM uint32_t  TMDBD;                        /*!< NTMS timer waveform dead time setting register                            */
  __IOM uint32_t  TMDBUB;                       /*!< NTMS timer waveform dead time setting register                            */
  __IOM uint32_t  TMDBDB;                       /*!< NTMS timer waveform dead time setting register                            */
  __IOM uint32_t  TMADCT;                       /*!< NTMS timer AD convert control register                                    */
  __IOM uint32_t  TMADA;                        /*!< NTMS timer AD convert start request timing register A                     */
  __IOM uint32_t  TMADAB;                       /*!< NTMS timer AD convert start request timing buffer register A              */
  __IOM uint32_t  TMADB;                        /*!< NTMS timer AD convert start request timing register B                     */
  __IOM uint32_t  TMADBB;                       /*!< NTMS timer AD convert start request timing buffer register B              */
} TMR0_NTMSnm_Type;                             /*!< Size = 140 (0x8c)                                                         */



/* =========================================================================================================================== */
/* ================                                          CODEOP                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CODEOP)
  */

typedef struct {                                /*!< CODEOP Structure                                                          */
  __IM  uint32_t  RESERVED;
  __IM  uint32_t  CODEOP0;                      /*!< Code option 0                                                             */
  __IM  uint32_t  CODEOP1;                      /*!< Code option 1                                                             */
} CODEOP_Type;                                  /*!< Size = 12 (0xc)                                                           */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define FLASHCNT_BASE               0x40000400UL
#define RESET_BASE                  0x40000200UL
#define CLKCNT_BASE                 0x40000300UL
#define NINT_BASE                   0x40000100UL
#define DMAC_BASE                   0x47000000UL
#define DMAC0_BASE                  0x47000100UL
#define DMAC1_BASE                  0x47000200UL
#define LTBC_BASE                   0x40004000UL
#define TIMER_BASE                  0x40001000UL
#define FTIMER_BASE                 0x40002000UL
#define RTC_BASE                    0x40005000UL
#define TIMER1K_BASE                0x40006000UL
#define WDT_BASE                    0x40003000UL
#define SSIOF0_BASE                 0x41000800UL
#define SSIOF1_BASE                 0x41000900UL
#define UARTF0_BASE                 0x41001800UL
#define I2CF0_BASE                  0x41002800UL
#define PORT2_BASE                  0x40010040UL
#define PORT3_BASE                  0x40010060UL
#define PORT4_BASE                  0x40010080UL
#define PORT5_BASE                  0x400100A0UL
#define PORT6_BASE                  0x400100C0UL
#define PORT7_BASE                  0x400100E0UL
#define PORT8_BASE                  0x40010100UL
#define SADC0_BASE                  0x42001000UL
#define CMP_BASE                    0x42002000UL
#define VLS_BASE                    0x42000000UL
#define LSICNT_BASE                 0x40000000UL
#define CRC_BASE                    0x44000000UL
#define AI_BASE                     0x46000000UL
#define CAN0_BASE                   0x47001000UL
#define TMR0_COMMON_BASE            0x40008000UL
#define TMR0_NTMS00_BASE            0x40008100UL
#define CODEOP_BASE                 0x40000480UL
#define UARTF1_BASE                 0x41001820UL
#define UARTF2_BASE                 0x41001840UL
#define UARTF3_BASE                 0x41001860UL
#define SADC1_BASE                  0x42001100UL
#define TMR0_NTMS01_BASE            0x40008200UL
#define TMR0_NTMS02_BASE            0x40008300UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define FLASHCNT                    ((FLASHCNT_Type*)          FLASHCNT_BASE)
#define RESET                       ((RESET_Type*)             RESET_BASE)
#define CLKCNT                      ((CLKCNT_Type*)            CLKCNT_BASE)
#define NINT                        ((NINT_Type*)              NINT_BASE)
#define DMAC                        ((DMAC_Type*)              DMAC_BASE)
#define DMAC0                       ((DMACn_Type*)             DMAC0_BASE)
#define DMAC1                       ((DMACn1_Type*)            DMAC1_BASE)
#define LTBC                        ((LTBC_Type*)              LTBC_BASE)
#define TIMER                       ((TIMER_Type*)             TIMER_BASE)
#define FTIMER                      ((FTIMER_Type*)            FTIMER_BASE)
#define RTC                         ((RTC_Type*)               RTC_BASE)
#define TIMER1K                     ((TIMER1K_Type*)           TIMER1K_BASE)
#define WDT                         ((WDT_Type*)               WDT_BASE)
#define SSIOF0                      ((SSIOFn_Type*)            SSIOF0_BASE)
#define SSIOF1                      ((SSIOFn1_Type*)           SSIOF1_BASE)
#define UARTF0                      ((UARTFn_Type*)            UARTF0_BASE)
#define I2CF0                       ((I2CFn_Type*)             I2CF0_BASE)
#define PORT2                       ((PORTn_Type*)             PORT2_BASE)
#define PORT3                       ((PORTn1_Type*)            PORT3_BASE)
#define PORT4                       ((PORTn2_Type*)            PORT4_BASE)
#define PORT5                       ((PORTn3_Type*)            PORT5_BASE)
#define PORT6                       ((PORTn4_Type*)            PORT6_BASE)
#define PORT7                       ((PORTn5_Type*)            PORT7_BASE)
#define PORT8                       ((PORTn6_Type*)            PORT8_BASE)
#define SADC0                       ((SADCn_Type*)             SADC0_BASE)
#define CMP                         ((CMP_Type*)               CMP_BASE)
#define VLS                         ((VLS_Type*)               VLS_BASE)
#define LSICNT                      ((LSICNT_Type*)            LSICNT_BASE)
#define CRC                         ((CRC_Type*)               CRC_BASE)
#define AI                          ((AI_Type*)                AI_BASE)
#define CAN0                        ((CANn_Type*)              CAN0_BASE)
#define TMR0_COMMON                 ((TMR0_COMMON_Type*)       TMR0_COMMON_BASE)
#define TMR0_NTMS00                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS00_BASE)
#define CODEOP                      ((CODEOP_Type*)            CODEOP_BASE)
#define UARTF1                      ((UARTFn_Type*)            UARTF1_BASE)
#define UARTF2                      ((UARTFn_Type*)            UARTF2_BASE)
#define UARTF3                      ((UARTFn_Type*)            UARTF3_BASE)
#define SADC1                       ((SADCn_Type*)             SADC1_BASE)
#define TMR0_NTMS01                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS01_BASE)
#define TMR0_NTMS02                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS02_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


#ifdef __cplusplus
}
#endif

#endif /* ML63Q25X7_H */


/** @} */ /* End of group ML63Q25x7 */

/** @} */ /* End of group ROHM Co.,Ltd. */
